name: Docs Publish

#v

on:
  push:
    branches:
      - master
  #  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            changed:
              - 'docs/**'
              - '.github/workflows/page.yml'

      - name: Install Node.js
        uses: actions/setup-node@v4
        if: ${{ steps.changes.outputs.changed == 'true' || startsWith(github.ref, 'refs/tags/') }}
        with:
          node-version: 18

      - name: Install dependencies
        if: ${{ steps.changes.outputs.changed == 'true' || startsWith(github.ref, 'refs/tags/') }}
        run: |
          npm install
      - name: Get commit information
        uses: rlespinasse/git-commit-data-action@v1
      - name: Add author to each Markdown file in notes
        run: |
          AUTHOR_NAME="${{ env.GIT_COMMIT_AUTHOR_NAME }}"
          AUTHOR_EMAIL="${{ env.GIT_COMMIT_AUTHOR_EMAIL }}"
          ls -lah .
          for file in $(find docs/notes -type f -name "*.md"); do
            # 获取当前文件的所有提交者
            AUTHORS=$(git log --follow --format='%an <%ae>' -- "$file" | sort | uniq | paste -sd ", " -)
            # 检查文件中是否已经包含作者信息  
            if ! grep -q "^作者：" "$file"; then
              # 将作者信息添加到文件的开头
              sed -i "1s/^/作者：$AUTHORS\n\n/" "$file"
            fi
          done
      - name: build
        if: ${{ steps.changes.outputs.changed == 'true' || startsWith(github.ref, 'refs/tags/') }}
        run: |
          npm run docs:build
          ls -al docs/.vitepress/dist
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ steps.changes.outputs.changed == 'true' || startsWith(github.ref, 'refs/tags/') }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vitepress/dist
