name: Docs Publish

#v

on:
  push:
    branches:
      - master
  #  pull_request:
  workflow_dispatch:
  workflow_run:
    workflows: ["Update Change Log", "Update Change Log2"] # 允许被 "Update Change Log2" 触发
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 克隆整个历史记录
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            changed:
              # - 'docs/**'
              # - '.github/workflows/page.yml'

      - name: Install Node.js
        uses: actions/setup-node@v4
        if: ${{ steps.changes.outputs.changed == 'true' || startsWith(github.ref, 'refs/tags/') }}
        with:
          node-version: 18

      - name: Install dependencies
        if: ${{ steps.changes.outputs.changed == 'true' || startsWith(github.ref, 'refs/tags/') }}
        run: |
          npm install
      - name: Add author to each Markdown file in notes
        run: |
          ls -lah .
          for file in $(find docs/notes -type f -name "*.md"); do
            # 获取当前文件的所有提交者
            AUTHORS=$(git log --follow --format='%an <%ae>' -- "$file" | sort | uniq | paste -sd ", " -)
            # 打印作者的信息
            echo "=========================================="
            echo "Markdown file: $file"
            echo "=========================================="
            echo "提交者：$AUTHORS"
            echo ""
            # 追加作者信息到 Markdown 文件中
            echo -e "作者：$AUTHORS\n\n$(cat "$file")" > "$file"
          done
      - name: build
        if: ${{ steps.changes.outputs.changed == 'true' || startsWith(github.ref, 'refs/tags/') }}
        run: |
          npm run docs:build
          ls -al docs/.vitepress/dist
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ steps.changes.outputs.changed == 'true' || startsWith(github.ref, 'refs/tags/') }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vitepress/dist
