name: Translate-test

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
            fetch-depth: 1
      - name: Auto Translate
        uses: offensive-vk/auto-translate@v7
        with:
            file: 'docs/**/*.md'
            language: 'es'           
      - name: 查看翻译后的文件
        run: |
           sudo apt-get update -y
           sudo apt-get install -y tree
           tree
       
 
    


